Retry on conflicts when labeling namespaces in tests
We're seeing this error:
```
broker_test_helper.go:216: Error annotating namespace: Operation cannot be fulfilled on namespaces "eventing-e2e7": the object has been modified; please apply your changes to the latest version and try again
```

Signed-off-by: Pierangelo Di Pilato <pdipilat@redhat.com>