fix unused linter error
Can be seen for example in: https://github.com/knative/eventing/actions/runs/21171606060/job/60889521311

```
  Error: pkg/requestreply/ingress_handler.go:352:6: func isResponseEvent is unused (unused)
  func isResponseEvent(event *cloudevents.Event, rr *v1alpha1.RequestReply) bool {
       ^
  Error: test/conformance/helpers/tracing_test_helper.go:53:3: const recordEventsPodName is unused (unused)
  		recordEventsPodName = "recordevents"
  		^
  Error: test/conformance/helpers/tracing_test_helper.go:98:6: func getTraceIDHeader is unused (unused)
  func getTraceIDHeader(t *testing.T, evInfos []recordevents.EventInfo) string {
       ^
  3 issues:
  * unused: 3
```